apiVersion: apps/v1
kind: Deployment
metadata: { name: sampleapp, labels: { app: sampleapp } }
spec:
  replicas: {{ .Values.replicaCount }}
  selector: { matchLabels: { app: sampleapp } }
  template:
    metadata: { labels: { app: sampleapp } }
    spec:
      containers:
      - name: sampleapp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports: [ { containerPort: 3000 } ]
        env:
        - { name: OTEL_EXPORTER_OTLP_ENDPOINT, value: "{{ .Values.otel.endpoint }}" }
        - { name: OTEL_EXPORTER_OTLP_PROTOCOL, value: "grpc" }
        - { name: OTEL_SERVICE_NAME, value: "{{ .Values.otel.serviceName }}" }
