version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=changeme
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
  - ./docker/kibana-config/kibana.yml:/usr/share/kibana/kibana.yml

  app:
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: otel-app
    environment:
      - OTEL_SERVICE_NAME=meu-app-node
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - elasticsearch
      - kibana
    ports:
      - "3000:3000"

volumes:
  esdata:
