version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=changeme
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.13
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - NODE_TLS_REJECT_UNAUTHORIZED=0


  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.13
    container_name: apm-server
    depends_on:
      - elasticsearch
    ports:
      - "8200:8200"
    environment:
      - output.elasticsearch.hosts=["http://elasticsearch:9200"]
      - output.elasticsearch.username=elastic
      - output.elasticsearch.password=changeme
    command: >
      apm-server -e
        -E apm-server.host=0.0.0.0:8200
        -E apm-server.secret_token=changeme
        -E setup.kibana.host=kibana:5601
        -E setup.kibana.username=elastic
        -E setup.kibana.password=changeme
        -E output.elasticsearch.enabled=true
        -E output.elasticsearch.hosts=["http://elasticsearch:9200"]
        -E output.elasticsearch.username=elastic
        -E output.elasticsearch.password=changeme

  otel-app:
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: otel-app
    depends_on:
      - apm-server
    ports:
      - "3000:3000"
    environment:
      - OTEL_SERVICE_NAME=meu-app-node
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://apm-server:8200
      - NODE_TLS_REJECT_UNAUTHORIZED=0

volumes:
  esdata:
