apiVersion: batch/v1
kind: Job
metadata:
  name: k6-smoke
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: k6
        image: grafana/k6:latest
        command: ["sh","-lc"]
        args:
          - >
            cat <<'JS' > /tmp/smoke.js &&
            import http from 'k6/http';
            import { sleep, check } from 'k6';
            export const options = {
              vus: 5, duration: '30s',
              thresholds: { http_req_failed: ['rate<0.01'], http_req_duration: ['p(95)<300'] }
            };
            const base = 'http://sampleapp.app.svc.cluster.local';
            export default function () {
              check(http.get(`${base}/login`),    {'200 login': r=>r.status===200});
              check(http.get(`${base}/checkout`), {'200 checkout': r=>r.status===200});
              http.get(`${base}/error`);
              sleep(1);
            }
            JS
            k6 run /tmp/smoke.js
