apiVersion: apps/v1
kind: Deployment
metadata: { name: sampleapp, namespace: cicd }
spec:
  replicas: 2
  selector: { matchLabels: { app: sampleapp } }
  strategy: { type: RollingUpdate, rollingUpdate: { maxUnavailable: 0, maxSurge: 1 } }
  template:
    metadata: { labels: { app: sampleapp } }
    spec:
      containers:
      - name: sampleapp
        image: sampleapp:__TAG__
        imagePullPolicy: IfNotPresent
        ports: [ { containerPort: 3000 } ]
        env:
        - { name: OTEL_EXPORTER_OTLP_ENDPOINT, value: "http://otel-collector.cicd.svc.cluster.local:4317" }
        - { name: OTEL_EXPORTER_OTLP_PROTOCOL, value: "grpc" }
        - { name: OTEL_SERVICE_NAME, value: "sampleapp" }
        readinessProbe: { httpGet: { path: /readyz,  port: 3000 }, initialDelaySeconds: 5, periodSeconds: 5 }
        livenessProbe:  { httpGet: { path: /healthz, port: 3000 }, initialDelaySeconds: 10, periodSeconds: 10 }
        resources: { requests: { cpu: "50m", memory: "64Mi" }, limits: { cpu: "500m", memory: "256Mi" } }
