groups:
  - name: example-alerts
    rules:
      - alert: SampleAppDown
        expr: up{job="sampleapp"} == 0
        for: 1m
        labels:
          severity: critical
          env: production
        annotations:
          summary: "SampleApp indisponível"
          description: "sampleapp está DOWN há >1m."

      - alert: HighErrorRate
        expr: sum(rate(sampleapp_http_requests_total{route="error"}[1m])) > 0.1
        for: 2m
        labels:
          severity: warning
          env: production
        annotations:
          summary: "Taxa de erro elevada"
          description: "Rota /error > 0.1 rps por >2m."

      - alert: PredictorDown
        expr: up{job="predictor"} == 0
        for: 1m
        labels:
          severity: critical
          env: production
        annotations:
          summary: "Predictor indisponível"
          description: "predictor está DOWN há >1m."
