global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: sampleapp
    metrics_path: /metrics
    static_configs:
      - targets: ['sampleapp:3000']

  - job_name: predictor
    metrics_path: /metrics
    static_configs:
      - targets: ['predictor:8000']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: otel-collector
    static_configs:
      - targets: ['otel-collector:8889','otel-collector:9464']

  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets: ['loki:3100']

  - job_name: tempo
    metrics_path: /metrics
    static_configs:
      - targets: ['tempo:3200']
